#!/usr/bin/env bash
#
# Back up the state this deployment cannot regenerate.
#
# Written because `king-audit.sh -d E` reported, on 2026-09-10, that ten Docker
# volumes existed and no backup mechanism of any kind did — no timer, no cron
# entry, no directory. That check had been abstaining with the words "this is a
# decision, not a check" until it was made to measure.
#
# WHAT IS BACKED UP, and why each earns its place
#
#   omniroute/data      66 MB. A BIND MOUNT, not a volume, which is why a
#                       volume-shaped question missed it. Holds the gateway's
#                       seven API keys and its call log. This deployment has
#                       already lost every key once, to a data directory owned
#                       by the wrong uid on restart, with zero errors logged.
#   king_agent-audit    The run journal and the vps_exec audit log. Nothing
#                       else records what the agent was asked or what it ran.
#   king_caddy-data     TLS certificates and ACME account state. Regenerable,
#                       but Let's Encrypt rate-limits, so losing this can mean
#                       hours without HTTPS rather than minutes.
#   king_ntfy-data      Topic state and subscriber records.
#   Neon Postgres       Every Activepieces flow, connection and run. External,
#                       so no volume backup would ever have touched it — a
#                       logical pg_dump is the only form that works.
#
# WHAT IS DELIBERATELY NOT
#
#   king_ollama-models  941 MB, and `ollama pull` reproduces it byte for byte.
#                       Backing it up would multiply the archive tenfold to
#                       protect against a download.
#   king_codegraph-out  87 MB, regenerated by scripts/codegraph-refresh.sh from
#                       the repo. A stale graph restored from backup is worse
#                       than an absent one: it answers confidently about code
#                       that has moved.
#   *-cache, redis      Caches and a work queue. Restoring either would replay
#                       or resurrect work, which is a fault, not a recovery.
#
# WHAT THIS DOES NOT PROTECT AGAINST, stated because a backup that overstates
# its coverage is worse than none: the archives live on THIS HOST. They survive
# a bad deploy, a `docker volume rm`, and a corrupted file. They do not survive
# the VM being destroyed. Moving them off-host needs a destination and a
# credential, which is a decision, not a script — and unlike the sentence this
# check used to carry, this one names what remains undone rather than using
# "it's a decision" to avoid measuring anything.
#
# Archives contain live credentials. The destination is outside the repo, mode
# 700, so it cannot be committed, is not inside the OpenHands mount, and is not
# world-readable.

set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
DEST="${KING_BACKUP_DIR:-$HOME/KING-backups}"
KEEP="${KING_BACKUP_KEEP:-7}"
PGIMAGE="postgres:16-alpine"

VOLUMES="king_agent-audit king_caddy-data king_ntfy-data"
BINDS="omniroute/data"

c_red()   { printf '\033[31m%s\033[0m' "$1"; }
c_green() { printf '\033[32m%s\033[0m' "$1"; }
c_dim()   { printf '\033[2m%s\033[0m' "$1"; }

# ---------------------------------------------------------------- self-test

self_test() {
    echo "self-test (fixtures only; no host, no secrets, no network)"
    _t=$(mktemp -d); _f=0

    # The retention arithmetic, which is the only pure logic here and the part
    # that can silently delete something it should have kept.
    mkdir -p "$_t/dest"
    for d in 01 02 03 04 05 06 07 08 09 10; do
        mkdir -p "$_t/dest/20260101-0000$d"
    done
    _keep=3
    # Same expression the real prune uses, against a fixture.
    _doomed=$(find "$_t/dest" -mindepth 1 -maxdepth 1 -type d | sort | head -n "-$_keep")
    _n=$(printf '%s\n' "$_doomed" | grep -c . || true)
    if [ "$_n" -eq 7 ]; then
        printf '  ok    keeping 3 of 10 marks exactly 7 for deletion\n'
    else
        printf '  FAIL  keeping 3 of 10 marked %s for deletion\n' "$_n"; _f=$((_f + 1))
    fi

    # And the direction that actually matters: the NEWEST must survive.
    if printf '%s\n' "$_doomed" | grep -q '2026010100000010$'; then
        printf '  FAIL  the newest archive was marked for deletion\n'; _f=$((_f + 1))
    else
        printf '  ok    the newest archive is never marked for deletion\n'
    fi

    # Fewer archives than the retention count must delete nothing. `head -n -3`
    # on a two-line input prints nothing, which is correct; the failure mode
    # would be a negative count wrapping into "delete everything".
    rm -rf "$_t/dest"; mkdir -p "$_t/dest/a" "$_t/dest/b"
    _doomed2=$(find "$_t/dest" -mindepth 1 -maxdepth 1 -type d | sort | head -n "-$_keep")
    if [ -z "$_doomed2" ]; then
        printf '  ok    fewer archives than the retention count deletes nothing\n'
    else
        printf '  FAIL  with 2 archives and keep=3 it would delete: %s\n' "$_doomed2"; _f=$((_f + 1))
    fi

    # A manifest that cannot be read back is a backup nobody can verify.
    printf 'path\tbytes\tsha256\n' > "$_t/manifest.tsv"
    printf 'x\t10\tdeadbeef\n' >> "$_t/manifest.tsv"
    if [ "$(awk -F'\t' 'NR>1 {n++} END {print n+0}' "$_t/manifest.tsv")" = "1" ]; then
        printf '  ok    the manifest parses as a tab table\n'
    else
        printf '  FAIL  the manifest does not parse\n'; _f=$((_f + 1))
    fi

    rm -rf "$_t"
    echo
    if [ "$_f" -eq 0 ]; then c_green "self-test passed"; echo; exit 0; fi
    c_red "$_f self-test check(s) failed"; echo; exit 1
}

# `[ ... ] && self_test` would be the last command when the test is false,
# so `set -e` would exit 1 on every ordinary run. This script documents that
# trap for other scripts; it does not get to commit it.
if [ "${1:-}" = "--self-test" ]; then self_test; fi

# ------------------------------------------------------------------- checks

command -v docker >/dev/null 2>&1 || { echo "docker is required" >&2; exit 2; }

STAMP=$(date -u '+%Y%m%d-%H%M%S')
OUT="$DEST/$STAMP"
mkdir -p "$OUT"
chmod 700 "$DEST" "$OUT"

echo "king backup — $STAMP"
c_dim "  into $OUT"; echo

fail=0
note() { printf '  %s  %s\n' "$1" "$2"; }

# ------------------------------------------------------------- bind mounts

for rel in $BINDS; do
    src="$REPO/$rel"
    name=$(printf '%s' "$rel" | tr '/' '-')
    if [ ! -d "$src" ]; then
        note "$(c_red 'MISS')" "$rel does not exist"; fail=$((fail + 1)); continue
    fi
    # Read as root: the gateway runs as uid 1000 inside but some paths under
    # data/ are written by the container's own user. `sudo -n` never prompts.
    if sudo -n tar -czf "$OUT/$name.tar.gz" -C "$REPO" "$rel" 2>/dev/null \
       || tar -czf "$OUT/$name.tar.gz" -C "$REPO" "$rel" 2>/dev/null; then
        sudo -n chown "$(id -u):$(id -g)" "$OUT/$name.tar.gz" 2>/dev/null || true
        note "$(c_green ' ok ')" "$rel → $name.tar.gz ($(du -h "$OUT/$name.tar.gz" | cut -f1))"
    else
        note "$(c_red 'FAIL')" "$rel could not be archived"; fail=$((fail + 1))
    fi
done

# ----------------------------------------------------------------- volumes

for vol in $VOLUMES; do
    if ! docker volume inspect "$vol" >/dev/null 2>&1; then
        note "$(c_red 'MISS')" "volume $vol does not exist"; fail=$((fail + 1)); continue
    fi
    # A throwaway container reads the volume with the right permissions,
    # instead of reaching into /var/lib/docker as root and hoping the layout
    # never changes.
    if docker run --rm -v "$vol:/src:ro" -v "$OUT:/dst" alpine:3.20 \
         tar -czf "/dst/$vol.tar.gz" -C /src . >/dev/null 2>&1; then
        note "$(c_green ' ok ')" "$vol → $vol.tar.gz ($(du -h "$OUT/$vol.tar.gz" | cut -f1))"
    else
        note "$(c_red 'FAIL')" "$vol could not be archived"; fail=$((fail + 1))
    fi
done

# ---------------------------------------------------------- external postgres

PGURL=$(sed -n 's/^AP_POSTGRES_URL=//p' "$REPO/activepieces/.env" 2>/dev/null | tail -1)
# Exported BEFORE the run that reads it. `docker run -e PGURL` takes the
# value from this process's environment, so an export placed after the call
# passes an empty variable and pg_dump fails with a confusing error rather
# than an obvious one.
export PGURL
if [ -z "$PGURL" ]; then
    note "$(c_red 'MISS')" "no AP_POSTGRES_URL; the Activepieces database is NOT backed up"
    fail=$((fail + 1))
else
    # The URL carries a password. It goes in via the environment, never as an
    # argument, so it cannot be read out of `ps` by any other user on the host.
    # Match pg_dump's major version to the server's, rather than pinning one.
    #
    # `pg_dump` refuses outright across a major mismatch — "aborting because of
    # server version mismatch" — while `psql` does not, which is why E-2 and
    # E-6 in the audit have been talking to this database happily with a
    # 16-series client. Neon was on 16 when those were written and is on 18.6
    # now. A pinned image would work until the next silent managed upgrade and
    # then stop, and the failure is a backup that does not happen.
    _srvnum=$(docker run --rm -e PGURL "$PGIMAGE" \
                sh -c 'psql "$PGURL" -At -c "show server_version_num"' 2>/dev/null || true)
    case "$_srvnum" in
        ''|*[!0-9]*) _dumpimg="$PGIMAGE" ;;
        *)           _dumpimg="postgres:$(( _srvnum / 10000 ))-alpine" ;;
    esac

    # Dump to a temporary name and promote it only once it exists and is not
    # empty. The first version wrote straight to the final path, and when
    # pg_dump aborted it left a ZERO-BYTE activepieces.dump — which the
    # manifest then listed, with the sha256 of the empty string, exactly as if
    # it were a backup. A backup that reports success it did not have is worse
    # than no backup: it is the same "could not read became zero" shape this
    # repo keeps catching, in the one place where the cost is the whole
    # database.
    if docker run --rm -e PGURL -v "$OUT:/dst" "$_dumpimg" \
         sh -c 'pg_dump "$PGURL" --no-owner --no-privileges -Fc -f /dst/.activepieces.part' \
         >/dev/null 2>&1 && [ -s "$OUT/.activepieces.part" ]
    then
        mv "$OUT/.activepieces.part" "$OUT/activepieces.dump"
        note "$(c_green ' ok ')" "Activepieces (Neon, server ${_srvnum:-?}) → activepieces.dump ($(du -h "$OUT/activepieces.dump" | cut -f1))"
    else
        rm -f "$OUT/.activepieces.part"
        note "$(c_red 'FAIL')" "pg_dump failed (client $_dumpimg vs server ${_srvnum:-unknown}); no file left behind"
        fail=$((fail + 1))
    fi
fi

# ---------------------------------------------------------------- manifest

# Two passes, deliberately. An empty archive is not an archive: listing one
# gives the manifest a row that reads as evidence and is its opposite. But the
# sweep cannot live inside the manifest's redirection — `{ … } > manifest.tsv`
# is not a subshell, so `note` keeps its variable updates and sends its warning
# straight into the file it is warning about.
for f in "$OUT"/*; do
    [ -f "$f" ] || continue
    case "$f" in *manifest.tsv) continue ;; esac
    if [ ! -s "$f" ]; then
        note "$(c_red 'FAIL')" "$(basename "$f") is zero bytes and was discarded"
        rm -f "$f"; fail=$((fail + 1))
    fi
done

{
    printf 'path\tbytes\tsha256\n'
    for f in "$OUT"/*; do
        [ -f "$f" ] || continue
        case "$f" in *manifest.tsv) continue ;; esac
        printf '%s\t%s\t%s\n' "$(basename "$f")" "$(wc -c < "$f")" "$(sha256sum "$f" | cut -d' ' -f1)"
    done
} > "$OUT/manifest.tsv"
chmod 600 "$OUT"/* 2>/dev/null || true

echo
c_dim "  manifest: $(awk -F'\t' 'NR>1 {n++} END {print n+0}' "$OUT/manifest.tsv") file(s), $(du -sh "$OUT" | cut -f1)"; echo

# ------------------------------------------------------------------- prune

# `sort` then `head -n -KEEP`: the timestamped directory names sort
# lexicographically into chronological order, so this always keeps the newest.
# The self-test asserts both that it marks the right count and that the newest
# is never among them, because a retention bug deletes silently and is only
# discovered on the day the backup is needed.
doomed=$(find "$DEST" -mindepth 1 -maxdepth 1 -type d | sort | head -n "-$KEEP" || true)
if [ -n "$doomed" ]; then
    printf '%s\n' "$doomed" | while read -r d; do
        [ -n "$d" ] || continue
        rm -rf "$d"
        c_dim "  pruned $(basename "$d")"; echo
    done
fi

if [ "$fail" -eq 0 ]; then
    c_green "backup complete"; echo
    exit 0
fi
c_red "$fail component(s) failed — this archive is INCOMPLETE"; echo
exit 1
